### ISSUE TITLE
Unfair advantage for pools with massive hashrate

### ISSUE THREAD

**Issue by RustyBlock** [electroneum/electroneum-pool#145]
Hi Electroneum Team, thanks for the great work you are doing. Looking forward to ETN taking over the World soon :)

We are running a small pool at https://www.etn.rustylock.club that was [doing quite well](https://www.etn.rustylock.club/#pool_blocks) until network hash-rate increased and, more importantly, most of the hashing power became concentrated on few pools like Nanopool (https://etn.nanopool.org/) or Spacepools (https://etn.spacepools.org/). Spacepools is much slower now but it was running 100 MH+ before Nanopool started.

Since network speed went significantly up, we observe efficiency of **all pools** going down, even the big ones report a lot of extra effort (e.g. quite a few high effort %s here https://etn.spacepools.org/#pool_blocks). Even whattomine has a notice about [negative luck on ETN mining](https://whattomine.com/). I think this is happening because replication of new blocks is taking about the same time it takes to find a new block so network is in constant update mode. Add rebuild operations (caused by forks) to the picture and you can see it looks quite grim. If pool manages to attract about **half of the network hashing power** or more, this is less of the problem for them because they start with new block immediately after they found the last one and chances are high they get the new one too so other pools have nothing to do but just refresh their daemons without making even one attempt at finding the next block.

Is it possible (_or did you even consider this_) to make an arbitrary increase of the difficulty to bring block detection time above 5 minutes so all pools have chances to find a new block but not only the ones that occupy 50% of the network hash-rate.

Hope this makes sense and other pool owners will join me in this request.

Kind regards
**RustyLock Team**

**Comment by aboljamajem** [comment]
I second this.

**Comment by bet0x** [comment]
I second this.

**Comment by cooltaby** [comment]
agree our pool died just because not getting any block even with hashing with 150 khs for 48 hours , thats sucks, all moved to mine another coin, too many orphan blocks

**Comment by RatusNatus** [comment]
"Is it possible (or did you even consider this) to make an arbitrary increase of the difficulty to bring block detection time above 5 minutes so all pools have chances to find a new block but not only the ones that occupy 50% of the network hash-rate."

I think this is a good idea to all starting coins when something like this happens.

**Comment by bobbieltd** [comment]
Young and small pools are in danger. We need to do something.

**Comment by phil2cr** [comment]
You are right and you can see that also clearly on AEON.

It is true that if the situation continue like that, our pool will also move to others coins !

**Comment by phil2cr** [comment]
I would like to add that:

It is even not in the interest of the big pool to kill little ones because:

The coin will look 'controled' and centralized so it will loose is value.

**Comment by phil2cr** [comment]
@RustyBlock
"Is it possible (or did you even consider this) to make an arbitrary increase of the difficulty to bring block detection time above 5 minutes" How do you think this could be implemented ?

**Comment by RustyBlock** [comment]
I didn't check the code yet, but there has to be the place where we calculate difficulty, just up it there. How to make sure everyone upgrades to the new version is a real question. Would be a soft fork situation with ETN guys needing to coordinate the upgrade. E.g. nodes upgrade and start "signaling" the new version support but still use old settings. Then when most of the nodes upgraded, switch network to new rules and old nodes stop to function.

**Comment by aboljamajem** [comment]
This does seem to be a cumbersome task, especially for Electroneum company that is already overwhelmed.
However, it seems either this, or leave everything as is leading to a potential 51% attack. Which could be huge since we are sitting on a $800mln market cap.

Do you think we should submit this to HackerOne as a potential vulnerability?

**Comment by cooltaby** [comment]
we have small pool www.asiaetnpool.com due to many days with 80 khs no block found all moved out now we broke and willing to close or sell it out :( its very hard to hit block

**Comment by RustyBlock** [comment]
@aboljamajem, I don't think there's conspiracy against Electroneum. Currency isn't doing anything yet and it will never be if people learn it was taken over by 51% attack. Link to the government website is just their company registration details, we can relax about 51% issue, however we can see the cases of market abuse by the big players that using the difficulty setting issue.

**Comment by dyablohunter** [comment]
I agree.

**Comment by bobbieltd** [comment]
We need a solution for small pools. I suggest a certification system formed by well known devs. They will check if the pool is sincere with the codes so miners are not worried when they want to mine with small pools. Avoiding scam pools too.

**Comment by Grimm2017** [comment]
Seriously?  You have no clue how pools work apparently.

**Comment by bet0x** [comment]
No, we want to avoid big pools taking everything, simple as that.

**Comment by RustyBlock** [comment]
@Grimm2017 is right, there is no such thing as "big pool", any pool can become big if they throw lot of money at nicehash or somehow attract a lot of mining power elsewhere, not important. It's not a problem, it's ok to have big pools (not more than 51% though). More of them is better for the currecny - it gets stable hashrate. The problem is the the mismatch between network's time to find a block and network's time to sync up. Now it's almost the same or network sync time is even longer so all miners get affetced - big and small but big are "less affected" or even have advantage since they can build new blocks on top of their own so network sync delay doesn't matter for them.

**Comment by bobbieltd** [comment]
I know that Grimm2017 points to block time and network difficulty but it doesn’t matter here. The principal issue is that small pools are dying.

**Comment by RustyBlock** [comment]
Yes, my suggestion is to slow everyone to the network rate. What's the point in finding blocks faster than we can get them synced around all blockchain? Also creates lot of issues for users of the blockchain who can get their transactions included in the chain that gets killed due to the softforks caused by this cray speed that network can't handle. It's a mess now.

**Comment by phil2cr** [comment]
@RustyBlock or make a fork or an other currency with quality in mind.

**Comment by oliverw** [comment]
[We](https://poolmining.org/pool/etn) endorse this proposal as well. Lately this has become a problem with many coins, not [just this one](https://www.dash.org/forum/threads/the-orphan-game-is-on-again.26588/).

**Comment by ch-ill** [comment]
Honestly what is the incentive to start a pool yourself after seeing something like this?

**Comment by phil2cr** [comment]
Yes, and there is more. Lot's of little pool decrease the fees. but without gaining more H/s.

One more easy solution could be pooling for new crypto, that way, making the currency less credible for a time. Is it is well explained to miner they could follow.  Little pools could recommand new cryptos and if miner are confident it is good for every body.
As peer electroneum, the communication seems, how to say ? Ambigous at least.

**Comment by aboljamajem** [comment]
@phil2cr  I actually did start a pool for GRAFT.  graftmine.net while keeping electromine.net running on 0% fees and no blocks since 10 days.

Once Electroneum fix this issue, I will recommend for users to jump back in.

**Comment by phil2cr** [comment]
In my opinion ETN was launched too quickly. Could be a good value in some years.
and yes you are right, i will also go to other crypto.

**Comment by Zer0dn** [comment]
Let me get this straight. 
You complain that you want the creators of the coin to control how it is mined and how it pays out?
That is a centralized problem which defeats the purpose of blockchain at its very core. 
If you had read the technical white papers the entirety of your blockchain solution and payout equations are in there. As for the pools that have the most you are correct however it is an inevitable issue where a site will have a problem and the miners will bail to another pool. That is how SpacePools grew so large because the early pools had issues and they were the only ones not having it and they had a low pool fee. 
That said I run my own pool as well. In a few months this argument will however become irrelevant as the startup pools that could not wait with no miners will have become impatient and quit. 
I have developed my own strategies to make my pool valuable to the coin. Do the same for yours if you want it to remain alive. It takes marketing, innovating, and above all good operations.

**Comment by aboljamajem** [comment]
No, we ask the developers to implement safety features that prevents/discourages transforming the decentralized solution to a centralized one

**Comment by Zer0dn** [comment]
It is controlled by the free market. Miners are free to mine from whatever pool they deem suits them best. 
While one mining pool submitting most of the blocks found does not mean that they are centralized because confirmations occur across the chain. 

The "creator" should not be the central source controlling the pools. The features were spelled out in the TWP. The market is swarming atm to a few major pools but like I said earlier that isn't something that the devs should control. That is no less centralized than the problem you want them to fix. The solution is to develop good pools that are ready to roll and still running when the pool that has the major population atm has a tech issue and the miners disperse. Having more working pools for them to land in means the network diversifies to a greater degree.

**Comment by phil2cr** [comment]
BTW remember : the creators of the cryptonight protocol (ETN is based on this one) precisly build it too avoid one big mining pool take the control over the currency :) !
They permit to avoid ASIC, but maybe didn't foreseen a coin attacked from start.

**Comment by RustyBlock** [comment]
@Zer0dn, looks like you're not yet understanding the point of the original request but offer generic business advice and conclusions which is right, of course, but your messages are beyond the subject of this discussion.
Difficulty calculation is in the code or the daemon, inside the net, nothing to do with centralization / decentralization matters you bring. Now it's set to 60 seconds which is way too low for this network size and speed. It's a hard change because modification of the way that difficulty is calculated on the network requires all nodes "rebuild".

**Potential solution:** targeting difficulty by **number of blocks** instead of the fixed time window might be a good idea that will remove big pool advantage, make every miner equal and rewarded according to the work they submitted to the network regardless of how and where they did it.

**Comment by Zer0dn** [comment]
No I understood it perfectly.

**Comment by bet0x** [comment]
@Zer0dn You didn't understand, now leave this talk to people who is actually looking for a solution. We are trying to get a solution on a low of issues, this is one of them, i will recommend something, if you cannot actually bring something to the table, stay away, sit and leave the talk to mature people because all your comment look like you are not ready to contribute to OSS.

**Comment by Zer0dn** [comment]
@bet0x how very presumptuous and ignorant of you. 
On that note I will do as you requested. 

I am not here to troll or harm this project and I apparently incense you.

Sorry for that.

**Comment by phil2cr** [comment]
"Too many forks, no one is contributing except a few"

Before even thinking of contribuing you have to understand and struggling with the code. Maybe that's why nobody contribute. I would like to contribute ! but before i understand all of these an other version will be on line :)

btw some bug fixed for some long time are even not contributed by the authors themself. Like the version 1.1.5 seems to have vanished.

@Zerodn has not my opinion but it is good to have the point of every one. Please calm down.

The solution of @RustyBlock could be a good one, the point is what to do if the dev team of ETN don't want to upgrade ?

**Comment by bittcoin555** [comment]
Ok how do i mine on ios apple phone or no these for cpu windows or mac and how do i add this
One http://electroneumpool.pw

**Comment by bet0x** [comment]
@bittcoin555 This is not a support thread. Don't go off topic.

**Comment by Namba06** [comment]
I agree.
We have a small pool http://electroneum.mining-pool.info started on January and after 14 days with 25KHs no block found.
It will be good if someone on Electroneum team could help small pool like us.
Should we have to update our pool ?
Thanks for help,
Regards,

**Comment by RustyBlock** [comment]
You can't do much to improve your pool performance, big or small, all are inefficient and wasting hashing power due to the issue with difficulty setting. If you look at other CryptoNote-based currencies, they set difficulty based on the expectation of 2 or more minutes for block. Electroneum network is running on the expectation of 60s that in reality brings us to almost 30s per block because people periodically push massive loads using Nicehash.

I haven't got much time for this recently but still planning to make a branch and test 4 minutes setting with testnet then issue a pull request suggesting difficulty expectation increase to 4 minutes and double the reward to make sure miners' profitability doesn't get affected.

**Comment by Namba06** [comment]
Thank you very much. I understand your answer, but do you think we will find a block one day or it has become impossible for a pool of our size?

**Comment by RustyBlock** [comment]
I can see you found your block 13 days ago so, if you didn't break anything since, you will find another one. You just need to ignore the estimated block time that pool is showing, it simply divides network difficulty by your pool speed assuming all your hashes are useful. However, in reality, lot of your hashing power is going against the future blocks that someone already found so your pool will just fails with a error that transaction is missing in transaction pool or something like this. If you check the logs, you may see you found more than one block but it was not accepted.

**Comment by phil2cr** [comment]
@RustyBlock Thanks for your work. Why not make a fork with your idea and create an other coin on it ?
Don't need an ICO if the coin is good for miners. Electroneum is online only since last november...

**Comment by briancfalls** [comment]
ucrypto dot com has not found a block since the old page was shut down by Amazon and the new page started up 11 days ago, it reset to zero Jan. 19th at 7:41 am and I lost 8 million hashes, I still have 3 million hashes afterward before I got booted from their Facebook page foe pointing this out, and not a single fraction of ETN paypout, they have just over 80 loyal miners still and no Blocks ever found. I am in easyhash getting ETN regular, with 2.7 Mh/s and 2,700 miners and blocks constantly found, but I am in us-etn-pool hashparty as well, and no block has been found for the past 2 days with a hash rate of 645 Kh/s and 1300 miners.

**Comment by RustyBlock** [comment]
@phil2cr I don't have time to run new coin and it makes little sense. technology is only 25% of success in this business.

**Comment by bet0x** [comment]
@phil2cr There is no point on running a fork or another coin. With all the ICO and stuff and alliances they should actually have time to fix this, wich is sad because we have no official response yet. Even nodes are having issues.

**Comment by phil2cr** [comment]
@RustyBlock @bet0x yes it is sad I don't think that will be fixed quickly. ICO and alliances take time, but on the long run the quality of the blockchain will be the only warranty : as there are so many coins to come ...
So why continue to loose hashrate ?

**Comment by PhillipVoyle** [comment]
I'm seeing the same problem on electroneum.mining-pool.info at the hash rate it's getting (22kh/s) it should find a block every week but has been live for 3 weeks with only one block found. Considering shifting to a larger pool where my machine's work counts for more.

**Comment by Pinto85** [comment]
Hi, i have a question, the speed of the pool can affect the time of block found? After 10 days i have found a block with 8Kh...I don't understand. My pool is cryptopool.top
Thanks

**Comment by bobbieltd** [comment]
@Pinto85 : speed of pool is the most important to find a block. Luck is the second but in the long run, luck is the same for all pools.

**Comment by Pinto85** [comment]
@bobbieltd thank, 
I'll explain better, I meant the speed of the server, network or other not hashrate...

**Comment by bobbieltd** [comment]
@Pinto85 Sorry, if your server isn’t overloaded ( no high CPU usage, no high RAM usage, no high bandwith usage ), it doesn’t affect block finding.

**Comment by Mrtops** [comment]
@electroneum do something please

**Comment by Pinto85** [comment]
I saw this pool, how is it possible that it took so many blocks with a hashrate so low? 
I would just like to understand better, thanks

**Comment by RustyBlock** [comment]
@Pinto85, see all payments made to one miner and number of hashes submitted is quite high despite the current speed and number of miners connected. Most likely this guy is using nicehash to buy bursts of very high speed so blocks are found quickly. Anyone can do it but you can also check and calculate his real profits which is likely negative so he is doing it for  making long term gains while suffering short term losses.

**Comment by bobbieltd** [comment]
@Pinto85 : That pool is FAKE and SCAM. If you carefully look at blocks found, they are WEIRD and NOT CORRECT. Cheating newbie miners 🤪🤪🤪

**Comment by bobbieltd** [comment]
Does anyone have a solution for young small pool ? My semiPOOL can’t compete with big pools 😰😰😰. Only few miners. Situation is worsen because luck keeps bad.

**Comment by cl0ck3r** [comment]
Electroneum is an shit coin!

**Comment by Pinto85** [comment]
I tested my pool for over 24 hours with 100Kh but no block found. 
There is something wrong @electroneum

**Comment by mounirrquiba** [comment]
Hello i have do some test after this issue posted results:

With 9.9MH/s for 24h -> 2 blocks
With 5 MHs fot 24H -> 1 block
With less -> no block


I have changed maxDiff from 2000 to 700000 but nothing happen better,
pool -> http://etncoin-pool.org 

Happy Mining and Happy fix!

**Comment by MrCoolLV** [comment]
@Pinto85 i agree with you, 120 pumped 120kh/s for 5 days and no block this all started happing "after" etn crash, soon after the rebuild no more blocks after the crash.. before the crash was fine block per day or other day

**Comment by reaperx7** [comment]
The pool I frequent, pool.hashusa.win has hit a heavy block for about a month now without a solve. It's getting worse. We were getting about 35kh/s and a block every 5-7 days. Since the big update, we have only gotten about 2kh/s and the block time has been over a month.

We can't compete against nicehash, and bigger pools hauling in hundreds of kh/s in power. Most of us have switched to the Android miner to get anything, but getting 10 ETN takes forever.

I don't want to say it but the block difficulty for larger pools needs to be adjusted so these pools averaging the rates they are getting get higher difficulty blocks while smaller pools get easier ones.

**Comment by reaperx7** [comment]
If anything, I'm mining GRF (graft) now. Its still cryptonote based so just some minor adjustments and I'm good to go.

**Comment by MrCoolLV** [comment]
I agree same issue with my pool, must of our miners now moved on because of the block issues from the big update

**Comment by reaperx7** [comment]
Unless the pool generation time is pushed back to at least 10-15 minutes per generation and pool search times pushed out to at least 20-30 minutes with 5 minutes wait for retries between seeks, this is going to get ugly. I really do not want to have to rely on 3-5 h/s for the rest of my ETN mining to get anything significant using the mobile miner. They also need to implement an orphan dumping mechanism to auto drop orphan blocks out of the network and pools to allow pools to get fresh blocks faster if orphans are found.

On Mar 21, 2018 6:04 AM, MrCoolLV <notifications@github.com> wrote:

I agree same issue with my pool, must of our miners now moved on because of the block issues from the big update

**Comment by Pinto85** [comment]
i understand that @electroneum is only marketing

**Comment by mounirrquiba** [comment]
Ok, let's try good diff coins: https://bbscoin.xyz or https://stellite.cash/

Happy Mining ;)

@RustyBlock @aboljamajem @bet0x @cooltaby @RatusNatus @Panthro @perl5577 @Pinto85 @phil2cr @PhillipVoyle 👍

**Comment by reaperx7** [comment]
The amount of available sponsored pools has shrank considerably since this issue was opened. Nanopools and Spacepools literally have choked everything out by causing redundant orphan blocks to get picked up by smaller pools which causes people to not want to mine.

If this trend continues two massive pools will control more than 51% of the block chain, which could cause a problem with mining efforts by independent miners and other pools. Remember if 51% of a blockchain can be controlled it has a higher risk of being attacked.

This is where the timed block generation measure and solving wait times and orphan checking and an orphan dumping system needed badly. Nobody wants to wait till an orphan block is solved only to hit more repeated orphans.

On May 1, 2018 4:17 AM, mobias <notifications@github.com> wrote:

@RustyBlock<https://github.com/RustyBlock> Please look at this electroneum/electroneum#197<https://github.com/electroneum/electroneum/issues/197>

**Comment by mobias** [comment]
We also close our pool because Nanopool has 51% hashing power.

**Comment by reaperx7** [comment]
I think a viable solution would be to do this:

- Set a mandatory timer of at least 5 minutes from the time of solving a block to picking up a new block generated.

- If a pool gets more than 20% hashing power of the entire blockchain, and the generation timer has not expired, the pool has to pick up a mandatory orphan block dumped by smaller pools.

- Any pools with less than 20% hashing power would be able to automatically dump an orphan block back into the blockchain and pick up a fresh generated block if one exists in the waiting list. No pools with less than 20% hashing power are required to solve an orphan block.

- If no orphan blocks exist in the network, all pools regardless of hashing power must still wait until the timer expires to pick up a new block, highest priority of pickup is reserved for lowest hashing power.

On May 1, 2018 4:53 AM, mobias <notifications@github.com> wrote:

We also close our pool because Nanopool has 51% hashing power.

**Comment by oliverw** [comment]
By now it should be pretty obvious that the people behind this project don't give a damn about a healthy mining ecosystem.

**Comment by MrCoolLV** [comment]
Yup, and is ok I won't be coming back to ETN

**Comment by reaperx7** [comment]
The problem is, unless its corrected in Monero, this problem is going to spread around all the cryptonote cryptocurrencies and eventually any dream of decentralization is going to be lost. Even implementing it in ETN or GRF would allow a backport to XMR and every other cryptonote out there.

The other problem is, the difficulty rating has exploded over the past no the due to this issue.

I would dare to accuse nanopools and spacepools of using specialized ASIC machines to gain an unfair advantage, but if I did, I might be correct, because even some miner rigs don't get the hashing power levels they're hitting by far.

On May 1, 2018 6:25 AM, MrCoolLV <notifications@github.com> wrote:

Yup, and is ok I won't be coming back to ETN

**Comment by RustyBlock** [comment]
In the new release (after 30th of May) we are getting 2 minutes for the block. Not 5, if course, but still good.
Mind that issie with block time is separate from asics problem. I started this request before aby asics arrived. 
Block timing of 1 minute is not a good choice because it's almost equal to the time needed to propagate the block data to most of the nodes. This means big part of the hashing power goes wasted, working for a block that is gone already, or creating orphans. 

New update introduces 2 minutes block time and revised block reward because now miners will be finding blocks less often. 
Combined with anti-asic measures, it will be awesome for the community.

**Comment by reaperx7** [comment]
Two minutes is a start, but you still have the problem of nano and space both grabbing extremely high hashing power where they can solve blocks in minutes. Five minutes, plus a prioritization rule set, plus a requirement of dedicating highest hashes for getting rid of orphans rather than just anyone, and making sure all pools have equal footing would be better still.

Its still going to be lopsided, but two minutes is a start, but when you have a unknown rig design generating 27,000,000+ h/s it's at least better than nothing to curb the problem.

On May 1, 2018 8:35 AM, RustyBlock <notifications@github.com> wrote:

In the new release (after 30th of May) we are getting 2 minutes for the block. Not 5, if course, but still good.
Mind that issie with block time is separate from asics problem. I started this request before aby asics arrived.
Block timing of 1 minute is not a good choice because it's almost equal to the time needed to propagate the block data to most of the nodes. This means big part of the hashing power goes wasted, working for a block that is gone already, or creating orphans.

New update introduces 2 minutes block time and revised block reward because now miners will be finding blocks less often.
Combined with anti-asic measures, it will be awesome for the community.

**Comment by mobias** [comment]
5 Minutes is a good choice.

**Comment by mobias** [comment]
after 30 May ETN network hashrate equal to 100 MH/s then we need to change time to 5 mins.

**Comment by RustyBlock** [comment]
Issue is addressed in the v2 release. Thank you for listening!
