### ISSUE TITLE
mined coins showing as paid on eupool webpage,but they're not in my paper wallet

### ISSUE THREAD

**Issue by marcusnoke** [electroneum/electroneum-pool#48]
Hi,,I have mined on the eupool and it shows on the web page i have been paid...transaction no 2e408a62cd7bea88e2f3fb438e48aa0594d233867e4181c3cc0549bdb2c7a2db
however the funds never reached my wallet,yet it has done from other pools..
when i click the transaction number on web page it says
can't get tx2e408a62cd7bea88e2f3fb438e48aa0594d233867e4181c3cc0549bdb2c7a2db
the wallet number on pool is correct and I've refreshed wallet several times..
hope you can help
cheers
marcus

**Comment by electroneumRepo** [comment]
Hi,

Please send an email to support@electroneum.com

**Comment by privacybtc** [comment]
Hi, I faced this problem and fixed it , problem in ur wallet
You must re build ur wallet by
get all ur wallet info saved : View key: secret: spendkey public: spendkey Recover Acsess
Then delete ur wallet file or move it away
open ur windows CMD
CD to ur wallet directory
then run the wallet by this command

electroneum-wallet-cli.exe --generate-from-keys CHANGENAME.etn

use new wallet name.etn
then put ur saved info
ur wallet will be rebuild and u will got ur money back.
I hope This problem must be fixed in next coins' blockchain update
