### ISSUE TITLE
About not get etn to my wallet

### ISSUE THREAD

**Issue by ganeshgot** [electroneum/electroneum-pool#60]
Yesterday I have bought 3595 etn coins 
from cryptopia and transfer them into my electroneum wallet but still the wallet does not show any balance..plz help me from this.

**Comment by electroneumRepo** [comment]
Firstly, this is not the place to open an issue. Issues regarding the wallet / transactions should be in the main electroneum repository. This repository is specifically for the pool.

You need to make sure that you have totally synced with the blockchain (leave electroneumd running).

Do NOT open the electroneum-wallet-cli until this is complete otherwise you will face issues.

If you having issues, there are plenty of videos on YouTube that give step by step instructions on how to do all of this.

**Comment by privacybtc** [comment]
Hi, I faced this problem and fixed it , problem in ur wallet
You must re build ur wallet by
get all ur wallet info saved : View key: secret: spendkey public: spendkey Recover Acsess
Then delete ur wallet file or move it away
open ur windows CMD
CD to ur wallet directory
then run the wallet by this command

electroneum-wallet-cli.exe --generate-from-keys CHANGENAME.etn

use new wallet name.etn
then put ur saved info
ur wallet will be rebuild and u will got ur money back.
I hope This problem must be fixed in next coins' blockchain update
